void writePGMP2(const char *filename, const image_t *image) {
    FILE *file = fopen(filename, "w");
    if (file == NULL) {
        perror("Error opening file");
        exit(EXIT_FAILURE);
    }

    // Write PGM header
    fprintf(file, "P2\n");
    fprintf(file, "# Generated by your program\n");
    fprintf(file, "%d %d\n", image->imagesize_x, image->imagesize_y);
    fprintf(file, "255\n");

    // Write pixel data
    for (int y = 0; y < image->imagesize_y; ++y) {
        for (int x = 0; x < image->imagesize_x; ++x) {
            fprintf(file, "%d ", image->pixel[x][y]);
        }
        fprintf(file, "\n");
    }

    fclose(file);
}
